[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
base="dark"
primaryColor="#00E5FF"
backgroundColor="#1E1E1E"
secondaryBackgroundColor="#2D2D2D"
textColor="#FFFFFF"
font="sans serif"
